use_frameworks!

platform :ios, '9.0'

target 'MultipleProductDemo_Example' do
  pod 'MultipleProductDemo', :path => '../'

  target 'MultipleProductDemo_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 4.0'
    pod 'Nimble', '~> 9.0'
  end
end
